/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./views/AboutUs.vue')['default']
    ApiExample: typeof import('./views/ApiExample.vue')['default']
    Btn: typeof import('./components/base/Btn.vue')['default']
    Card: typeof import('./components/base/Card.vue')['default']
    Check: typeof import('./components/Check.vue')['default']
    Features: typeof import('./views/Features.vue')['default']
    Footer: typeof import('./components/core/Footer.vue')['default']
    Guarantees: typeof import('./views/Guarantees.vue')['default']
    Hero: typeof import('./views/Hero.vue')['default']
    ImgCard: typeof import('./components/base/ImgCard.vue')['default']
    InfoCard: typeof import('./components/base/InfoCard.vue')['default']
    LeftBlob: typeof import('./components/core/LeftBlob.vue')['default']
    Market: typeof import('./views/Market.vue')['default']
    RightBlob: typeof import('./components/core/RightBlob.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stack: typeof import('./views/Stack.vue')['default']
    StayInformed: typeof import('./views/StayInformed.vue')['default']
    Subheading: typeof import('./components/base/Subheading.vue')['default']
    Subscribe: typeof import('./components/Subscribe.vue')['default']
    Toolbar: typeof import('./components/core/Toolbar.vue')['default']
    TopBlob: typeof import('./components/core/TopBlob.vue')['default']
    View: typeof import('./components/core/View.vue')['default']
    VVideo: typeof import('./views/VVideo.vue')['default']
  }
}
